### ISSUE TITLE
IT email

### ISSUE THREAD

**Issue by taramoran** [MOC-Alliance-Admin/events#1]

**Comment by taramoran** [comment]
Greetings,
We are again detecting open instances of Advanced Message Queuing
Protocol (AMQP) and Erlang Port Mapper Daemon (EPMD) on this host.  In
early November, we had received a report that these instances were shut
down and that the host would be turned off "shortly".  Did this host get
powered up again?  Please secure that this host / AMQP and EPMD
instances are properly restricted or offline. 

Thanks, 

Incident Response Team

**Comment by msdisme** [comment]
Created a ticket in osticket for team /Naved to review and notified IRT.
