### ISSUE TITLE
appoint discussion leaders

### ISSUE THREAD

**Issue by taramoran** [MOC-Alliance-Admin/events#5]
Identify BOAF “seeded meetings” decide on proposed leaders - 
- Open Operations
         - Augustine and Justin
- Accelerators/FPGAS  - potentially just a  tutorial
         - Suranga Handagala	
- Domain researchers and users    
          - Milson
- Data Repositories, Sharing & Storage - OSN/NESE? 
   - One of the IBM folks, Jim? via Orran
- Medicine and Medical research 
   - Piotr and Rudolph
- ESI
   - Mainn or Gagan or Heidi

**Comment by msdisme** [comment]
Milson asked
Wayne and Augustine asked
Suranga agreed
Piotr, IBM, to be asked
Gagan/Mainn on tap

**Comment by msdisme** [comment]
Piotr/Rudolph to be asked still

**Comment by joachimweyl** [comment]
@msdisme what are the next steps on this?

**Comment by msdisme** [comment]
Done - all should have received mail.
